[package]
name = "wasmide"
version = "0.1.0"
edition = "2021"
authors = ["Benjamin Lefebvre"]
categories = ["wasm", "web-programming"]
description = "An exprimental frontend framework in pure rust"
keywords = ["framework", "wasm", "web"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/L-Benjamin/wasmide"

[dependencies.wasm-bindgen]
version = "0.2.79"
default-features = false

[dependencies.web-sys]
version = "0.3.56"
default-features = false
features = [
    "Document",
    "HtmlElement",
    "Node",
    "Window",
]